/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_xknowledge_se_jni_Register */

#ifndef _Included_com_java_xknowledge_se_jni_Register
#define _Included_com_java_xknowledge_se_jni_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_xknowledge_se_jni_Register
 * Method:    HelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_java_xknowledge_se_jni_Register_HelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
