/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_xknowledge_se_jni_string_StringTest */

#ifndef _Included_com_java_xknowledge_se_jni_string_StringTest
#define _Included_com_java_xknowledge_se_jni_string_StringTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_xknowledge_se_jni_string_StringTest
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_java_xknowledge_se_jni_string_StringTest_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
