/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_xknowledge_se_jni_reference_Reference */

#ifndef _Included_com_java_xknowledge_se_jni_reference_Reference
#define _Included_com_java_xknowledge_se_jni_reference_Reference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_xknowledge_se_jni_reference_Reference
 * Method:    callJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_java_xknowledge_se_jni_reference_Reference_callJavaStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_java_xknowledge_se_jni_reference_Reference
 * Method:    callJavaInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_java_xknowledge_se_jni_reference_Reference_callJavaInstanceMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
